from dataclasses import dataclass
from typing import Iterable, Optional

from mahjong.shanten import Shanten

from .constant import (
    CLAIM_PRIORITY,
    CHI_ACTIONS,
    KAN_OPEN,
    NUM_SEATS,
    PON,
    RON,
)
from .events import ClaimsGenerated, DomainEvent, NoYakuEncountered
from .scoring import HandValue, ScoringService
from .state import ClaimPhase, ClaimStage, DiscardRef, GameState


@dataclass(frozen=True)
class PendingClaim:
    """An individual legacy action offer generated by one discard."""

    claimant: int
    action: int
    from_seat: int
    discard_tile34: int
    chi_sequence: Optional[tuple[int, int, int]] = None
    score_result: Optional[HandValue] = None


@dataclass(frozen=True)
class ClaimBuildResult:
    claims: list[PendingClaim]
    events: tuple[DomainEvent, ...]


class ClaimBuilder:
    """Build all possible claims without deciding their eventual outcome."""

    def __init__(self, shanten_calc: Shanten, scoring: ScoringService) -> None:
        self._shanten = shanten_calc
        self._scoring = scoring

    def build(
        self,
        state: GameState,
        discarder: int,
        tile34: int,
    ) -> ClaimBuildResult:
        claims: list[PendingClaim] = []
        events: list[DomainEvent] = []

        for seat in range(NUM_SEATS):
            if seat == discarder:
                continue
            claimant = state.players[seat]

            temporary = claimant.hand.copy()
            temporary.add(tile34)
            if temporary.shanten(self._shanten) == -1:
                score = self._scoring.estimate_ron(state, seat, discarder, tile34)
                if score.is_valid:
                    claims.append(
                        PendingClaim(
                            claimant=seat,
                            action=RON,
                            from_seat=discarder,
                            discard_tile34=tile34,
                            score_result=score,
                        )
                    )
                elif score.error == self._scoring.no_yaku_error:
                    events.append(
                        NoYakuEncountered(
                            discarder=discarder,
                            claimant=seat,
                            tile34=tile34,
                        )
                    )

            if claimant.state.riichi:
                continue

            count = claimant.hand.count(tile34)
            if count == 3 and state.kan_count < 4 and state.wall.remaining_live() > 0:
                claims.append(PendingClaim(seat, KAN_OPEN, discarder, tile34))
            if count >= 2:
                claims.append(PendingClaim(seat, PON, discarder, tile34))

            left_seat = (discarder + 1) % NUM_SEATS
            if seat == left_seat:
                for option in claimant.hand.possible_chi(tile34):
                    claims.append(
                        PendingClaim(
                            claimant=seat,
                            action=option.action,
                            from_seat=discarder,
                            discard_tile34=tile34,
                            chi_sequence=option.sequence,
                        )
                    )

        claims.sort(
            key=lambda claim: (
                CLAIM_PRIORITY.get(claim.action, 99),
                self._seat_distance(discarder, claim.claimant),
            )
        )
        if claims:
            events.append(
                ClaimsGenerated(
                    discarder=discarder,
                    tile34=tile34,
                    claims=tuple((claim.claimant, claim.action) for claim in claims),
                )
            )
        return ClaimBuildResult(claims=claims, events=tuple(events))

    @staticmethod
    def _seat_distance(from_seat: int, to_seat: int) -> int:
        distance = (to_seat - from_seat) % NUM_SEATS
        return distance if distance else NUM_SEATS


def first_claim_stage(claims: Iterable[PendingClaim]) -> Optional[ClaimStage]:
    claim_list = list(claims)
    if any(claim.action == RON for claim in claim_list):
        return ClaimStage.RON
    if any(claim.action == KAN_OPEN for claim in claim_list):
        return ClaimStage.KAN_OPEN
    if any(claim.action == PON for claim in claim_list):
        return ClaimStage.PON
    if any(claim.action in CHI_ACTIONS for claim in claim_list):
        return ClaimStage.CHI
    return None


def make_claim_phase(discard: DiscardRef, claims: list[PendingClaim]) -> ClaimPhase:
    stage = first_claim_stage(claims)
    if stage is None:
        raise ValueError("cannot make claim phase without claims")
    return ClaimPhase(discard=discard, pending_claims=claims, stage=stage)


def claims_in_stage(
    phase: ClaimPhase, stage: Optional[ClaimStage] = None
) -> list[PendingClaim]:
    use_stage = stage or phase.stage
    action_for_stage = {
        ClaimStage.RON: (RON,),
        ClaimStage.KAN_OPEN: (KAN_OPEN,),
        ClaimStage.PON: (PON,),
        ClaimStage.CHI: CHI_ACTIONS,
    }[use_stage]
    candidates = [
        claim for claim in phase.pending_claims if claim.action in action_for_stage
    ]
    return sorted(
        candidates, key=lambda claim: _seat_distance(phase.discard.seat, claim.claimant)
    )


def current_offers(phase: ClaimPhase) -> list[PendingClaim]:
    candidates = claims_in_stage(phase)
    if not candidates:
        raise RuntimeError(f"no claims in active stage {phase.stage}")
    if phase.stage == ClaimStage.CHI:
        # Only the player to the discarder's left can chi.  Keep all three
        # legacy chi action ids available in the same prompt.
        claimant = candidates[0].claimant
        return [claim for claim in candidates if claim.claimant == claimant]
    if not 0 <= phase.cursor < len(candidates):
        raise RuntimeError("claim cursor outside active stage")
    return [candidates[phase.cursor]]


def current_claimant(phase: ClaimPhase) -> int:
    return current_offers(phase)[0].claimant


def advance_after_pass(phase: ClaimPhase) -> bool:
    """Advance a passed prompt; return ``True`` when a new prompt exists."""
    candidates = claims_in_stage(phase)
    if phase.stage != ClaimStage.CHI and phase.cursor + 1 < len(candidates):
        phase.cursor += 1
        return True
    return advance_stage(phase)


def advance_after_ron(phase: ClaimPhase) -> bool:
    """Advance among ron candidates only; lower-priority calls are suppressed."""
    candidates = claims_in_stage(phase, ClaimStage.RON)
    if phase.cursor + 1 < len(candidates):
        phase.cursor += 1
        return True
    return False


def advance_stage(phase: ClaimPhase) -> bool:
    stages = (ClaimStage.RON, ClaimStage.KAN_OPEN, ClaimStage.PON, ClaimStage.CHI)
    current_index = stages.index(phase.stage)
    for stage in stages[current_index + 1 :]:
        if claims_in_stage(phase, stage):
            phase.stage = stage
            phase.cursor = 0
            return True
    return False


def same_suit_consecutive(sequence: tuple[int, int, int]) -> bool:
    ordered = sorted(sequence)
    return (
        ordered[2] < 27
        and ordered[0] + 1 == ordered[1]
        and ordered[1] + 1 == ordered[2]
        and ordered[0] // 9 == ordered[2] // 9
    )


def _seat_distance(from_seat: int, to_seat: int) -> int:
    distance = (to_seat - from_seat) % NUM_SEATS
    return distance if distance else NUM_SEATS
